use_frameworks!

platform :ios, '10.0'
install! 'cocoapods', :disable_input_output_paths => true

target 'FoodTrackerModelLib_Example' do
  pod 'FoodTrackerModelLib', :path => '../'

  target 'FoodTrackerModelLib_Tests' do
    inherit! :search_paths


  end
end
